/* Ercan Abi seslendirmesi (edge-tts, tr-TR-AhmetNeural). Üretici: ses/_ercan_ses.py */
window.ERCAN_SES = {
"Hocam, elli sekiz yaşında bir amca. Yarım saattir göğsünde bir ağırlık var, terli geldi.": "ses/ercan/e000.mp3",
"Kapıdan girerken elini göğsünden ayırmadı hocam. Ben monitöre hazırım.": "ses/ercan/e001.mp3",
"Hocam, amcanın yüzü kül gibi. Vakit kaybetmeyelim.": "ses/ercan/e002.mp3",
"Hocam, yirmi sekiz yaşında bir delikanlı. Karnı dünden beri ağrıyormuş, eliyle sağ altı tutuyor.": "ses/ercan/e003.mp3",
"Dünden beri bir şey yememiş hocam. Bir bakar mısın?": "ses/ercan/e004.mp3",
"Genç hasta hocam, sağ alt karın. Acelesi yok gibi duruyor ama ben o kadar emin değilim.": "ses/ercan/e005.mp3",
"Hocam, yirmi dört yaşında bir hanım. Bahçede çiçek sularken arı sokmuş, boğazı şişiyor!": "ses/ercan/e006.mp3",
"Hocam, hızlı! Dudağı şişmiş, hırıltılı soluyor.": "ses/ercan/e007.mp3",
"Hocam, bu hastayı bekletemeyiz. Gözünün kapağına bak, dudağına bak.": "ses/ercan/e008.mp3",
"Hocam, kırk bir yaşında bir hanım. Gece başı çatlamış, iki kere kusmuş. Kocası getirdi, onun da rengi pek iyi değil.": "ses/ercan/e009.mp3",
"Hocam, baş ağrısı, bulantı, kucağında kusma kabı. Saturasyonu iyi görünüyor ama bende bir tuhaflık var.": "ses/ercan/e010.mp3",
"Hocam, hastaya bir bakar mısın?": "ses/ercan/e011.mp3",
"Hocam, durum değişti. Şimdi!": "ses/ercan/e012.mp3",
"Rengi attı hocam, bak.": "ses/ercan/e013.mp3",
"Hocam, bu gidiş iyi değil.": "ses/ercan/e014.mp3",
"Hocam, tansiyon düştü, alnı soğuk terle doldu!": "ses/ercan/e015.mp3",
"Amcanın rengi gri hocam. Bu iş artık beklemez.": "ses/ercan/e016.mp3",
"Bu adam kayıyor hocam. Telefon ne zaman açılacak?": "ses/ercan/e017.mp3",
"Hocam, ateşi çıktı, dizlerini karnına çekti. Karnına dokundurmuyor!": "ses/ercan/e018.mp3",
"Karın tahta gibi oldu hocam. Bu çocuk kötüleşti.": "ses/ercan/e019.mp3",
"Nabız yüz on sekiz hocam. Bak ona.": "ses/ercan/e020.mp3",
"Hocam, dudakları mor! Hışırtı çıkarıyor, nefes alamıyor!": "ses/ercan/e021.mp3",
"Tansiyon yetmiş hocam, hemen bir şey yapmamız lazım!": "ses/ercan/e022.mp3",
"Saturasyon seksen beş hocam! Boğazını tutuyor!": "ses/ercan/e023.mp3",
"Hocam, uykuya kayıyor! Sorulara cevap vermiyor.": "ses/ercan/e024.mp3",
"Hocam, kafası karıştı, nerede olduğunu bilmiyor!": "ses/ercan/e025.mp3",
"Hocam, kasılıyor! Nöbet!": "ses/ercan/e026.mp3",
"Hocam, saat işliyor. Unuttuğun bir şey var gibi.": "ses/ercan/e027.mp3",
"Bir şeyin zamanı geçti hocam. Ben söyledim sanma.": "ses/ercan/e028.mp3",
"Hocam, o iş bu saatte yapılırdı. Bir bakar mısın?": "ses/ercan/e029.mp3",
"Süre doldu hocam. Not aldım.": "ses/ercan/e030.mp3",
"Hocam, hastanın rakamını bilmiyoruz.": "ses/ercan/e031.mp3",
"Hocam, nabız, tansiyon, saturasyon... Hiçbirini görmedik. Ben bağlayayım mı?": "ses/ercan/e032.mp3",
"Hocam, rakamsız hasta kör uçuş demek.": "ses/ercan/e033.mp3",
"Hocam, bu hastaya ne söyleyecek bu tetkik?": "ses/ercan/e034.mp3",
"Hocam, bu tetkik sonuç gelince hastaya bir şey katar mı?": "ses/ercan/e035.mp3",
"Bunun parası var, vakti var hocam.": "ses/ercan/e036.mp3",
"Hocam, hastayı BT'ye götürürsek monitörden uzak kalır. Gerekli mi?": "ses/ercan/e037.mp3",
"Hocam, radyoloji sırası uzun. Bu hastanın o kadar vakti var mı?": "ses/ercan/e038.mp3",
"Hocam, bunun sonucu bir saat sonra gelir. Hasta ne yapsın o zamana kadar?": "ses/ercan/e039.mp3",
"Hocam, bunu bir daha konuşmayalım.": "ses/ercan/e040.mp3",
"Hocam, emri verdin ama ben yapmadan bir daha düşünmeni isterdim.": "ses/ercan/e041.mp3",
"Not aldım hocam.": "ses/ercan/e042.mp3",
"Hocam, hasta bunu kaldırmaz.": "ses/ercan/e043.mp3",
"Hocam, bu hastada ne için adrenalin? Kalbi zaten yoruluyor.": "ses/ercan/e044.mp3",
"Hocam, damardan bolus mu? Ritim bozulabilir, bu iş böyle yapılmaz.": "ses/ercan/e045.mp3",
"Hocam, tansiyon düşükken dil altı nitrat mı? Elini çek.": "ses/ercan/e046.mp3",
"Hocam, bu hastayı bu hâlde mi gönderdin? Ben kapıyı açmazdım.": "ses/ercan/e047.mp3",
"Bak şimdi oldu.": "ses/ercan/e048.mp3",
"Hm. Tamam hocam.": "ses/ercan/e049.mp3",
"İşte bu. Sıradaki?": "ses/ercan/e050.mp3",
"Bak şimdi oldu. Kâğıt birazdan elinde, yorum senin.": "ses/ercan/e051.mp3",
"Hocam, kardiyolojiye haber gitti. Tahlili beklemedin, iyi ettin.": "ses/ercan/e052.mp3",
"Hocam, çiğnetiyorum. Bu ucuz ilaç bazen çok şey yapar.": "ses/ercan/e053.mp3",
"Rakamlar ekranda hocam. Artık kör değiliz.": "ses/ercan/e054.mp3",
"Damar yolu açık hocam. Kan da hazır.": "ses/ercan/e055.mp3",
"Hocam, ağzına bir şey vermeyeceğim. Hasta aç, doğru.": "ses/ercan/e056.mp3",
"Hocam, ağrı kesiciyi geciktirmemen iyi oldu. Ağrıyan hasta anlatamaz.": "ses/ercan/e057.mp3",
"Cerrahi nöbetçisi yolda hocam. Zamanında aradın.": "ses/ercan/e058.mp3",
"Bak şimdi oldu. Uyluğa yaptım hocam.": "ses/ercan/e059.mp3",
"İşte bu hocam, ilk ilaç buydu.": "ses/ercan/e060.mp3",
"Bacaklarını kaldırdım hocam, tansiyon toparlar.": "ses/ercan/e061.mp3",
"Maske takıldı hocam, yüksek akım.": "ses/ercan/e062.mp3",
"Gözleme aldım hocam. Bu hastayı erken göndermeyelim, iyi karar.": "ses/ercan/e063.mp3",
"Hocam, sonuç geldi. Bir bakar mısın?": "ses/ercan/e064.mp3",
"Sonuç elimde hocam, yorum senin.": "ses/ercan/e065.mp3",
"Hocam, bu sonuçla iş değişir.": "ses/ercan/e066.mp3",
"Hocam, kâğıtta bir şey var. Ön taraftaki derivasyonlara bak.": "ses/ercan/e067.mp3",
"Hocam, troponin geldi. Ama sen bunu beklemeden de karar verebilirdin, değil mi?": "ses/ercan/e068.mp3",
"CRP de geldi hocam. Tablo birbirini tutuyor mu, bir bak.": "ses/ercan/e069.mp3",
"Hocam, hasta orada.": "ses/ercan/e070.mp3",
"Hocam, çay soğur ama hasta soğumasın.": "ses/ercan/e071.mp3",
"Hocam, ben bekliyorum; hasta da bekliyor.": "ses/ercan/e072.mp3",
"Hocam? Emir verecek misin?": "ses/ercan/e073.mp3",
"Hocam, rakamlar toparlıyor.": "ses/ercan/e074.mp3",
"Rengi geldi hocam. Ama gözümüzü ayırmayalım.": "ses/ercan/e075.mp3",
"Hocam, ağrısı hafifledi, konuşabiliyor. Ama muayene bulguları duruyor, değil mi?": "ses/ercan/e076.mp3",
"Çocuk rahatladı hocam, ama bu rahatlık karnın içindekini değiştirmedi.": "ses/ercan/e077.mp3",
"Nefesi rahatladı hocam, hırıltı azaldı!": "ses/ercan/e078.mp3",
"Hocam, konuşabiliyor artık. Ama gözlemden çıkarmayalım.": "ses/ercan/e079.mp3",
"Hocam, maske işe yaradı. Gözleri açıldı, başı daha az ağrıyormuş.": "ses/ercan/e080.mp3",
"Rengi geliyor hocam. Oksijen dediğin böyle bir şey.": "ses/ercan/e081.mp3",
"İyi nöbetti hocam.": "ses/ercan/e082.mp3",
"Hm. Bu sefer not aldım ama iyi taraftan.": "ses/ercan/e083.mp3",
"Hocam, sana bir şey diyeceğim: iyiydin.": "ses/ercan/e084.mp3",
"Hocam, amca kateter laboratuvarına zamanında girdi. Bu iş böyle yapılır.": "ses/ercan/e085.mp3",
"Cerrahi aldı hocam. Çocuk patlamadan gitti.": "ses/ercan/e086.mp3",
"Hanım gözlemde hocam. İlk ilaç doğru yerdeydi.": "ses/ercan/e087.mp3",
"Hocam, evdekilerin hepsi geldi, COHb'leri yüksekti. Bir aileyi kurtardın, bunu unutma.": "ses/ercan/e088.mp3",
"Hocam, bu hasta kurtuldu ama biz şanslıydık.": "ses/ercan/e089.mp3",
"Bir daha olursa ilk dakikaya bakalım hocam.": "ses/ercan/e090.mp3",
"Not aldım hocam. Hepsini.": "ses/ercan/e091.mp3",
"Hocam, amca yetişti ama kalbin bir kısmı geç kaldı.": "ses/ercan/e092.mp3",
"Bu kadar beklemek gerekmiyordu hocam.": "ses/ercan/e093.mp3",
"Hanım toparladı ama dudaklar morarırken çok geç kalmıştık.": "ses/ercan/e094.mp3",
"Hanım toparladı ama evdekileri düşünmeden olmazdı hocam. Soba hâlâ yanıyor olabilir.": "ses/ercan/e095.mp3",
"Bu iş bazen böyle olur hocam. Ama bazen olmazdı.": "ses/ercan/e096.mp3",
"Yirmi bir yıldır bu kapıdan giriyorum. Alışılmıyor.": "ses/ercan/e097.mp3",
"Bu hastayı kateter laboratuvarında görmemiz gerekiyordu hocam.": "ses/ercan/e098.mp3",
"Hocam, bu çocuk bu yaşta, bu kadar kolay bir tablodan gitmemeliydi.": "ses/ercan/e099.mp3",
"Hocam, o çanta yanımızdaydı.": "ses/ercan/e100.mp3",
"Hocam, göğüs ağrısında ilk iş: monitör, damar yolu ve EKG. İlk on dakikada EKG çekilmiş olmalı.": "ses/ercan/e101.mp3",
"EKG'de ön derivasyonlara bak, V1'den V4'e. ST yükselmesi varsa troponini bekleme; bu tanı EKG ile konur.": "ses/ercan/e102.mp3",
"Açık konuşayım hocam: aspirin çiğnet, kardiyolojiyi ara, primer PKG için kateter laboratuvarını açtır. Troponini bekleme.": "ses/ercan/e103.mp3",
"Hocam, ağrı nerede başladı, nereye gitti, onu sor. Sonra karnına bak, özellikle sağ alta.": "ses/ercan/e104.mp3",
"Hemogram ve CRP iste, görüntüleme için USG. Ağrısını da kes: IV ağrı kesici tanıyı maskelemez.": "ses/ercan/e105.mp3",
"Ağızdan alımı kes, damar yolu aç, serum başla, genel cerrahiyi ara. Bu çocuk ameliyata gidiyor hocam.": "ses/ercan/e106.mp3",
"Hocam, arı sokması, şişen dudak, hırıltı, düşük tansiyon. Bu hasta dakikalarla yarışıyor, tetkik bekleme.": "ses/ercan/e107.mp3",
"İlk ilaç adrenalin: 0,5 mg, kas içine, uyluğun dış yanına. Damardan değil.": "ses/ercan/e108.mp3",
"Adrenalinden sonra oksijen ver, yatırıp bacaklarını kaldır, damar yolu açıp sıvı ver. Antihistaminik en sona. Sonra gözleme al; reaksiyon geri dönebilir.": "ses/ercan/e109.mp3",
"Hocam, kış gecesi, aynı evden gelen, başı ağrıyan bir aile... Evin nasıl ısındığını sor.": "ses/ercan/e110.mp3",
"Saturasyonun yüzde doksan sekiz olmasına aldanma. Nabız oksimetresi karbonmonoksiti ayırt edemez; kan gazında COHb'ye bak.": "ses/ercan/e111.mp3",
"Açık konuşayım: geri solumasız maskeyle yüzde yüz oksijen, kan gazında COHb, monitör. Evdekileri acile çağır. COHb yüksekse hiperbarik merkeze danış.": "ses/ercan/e112.mp3",
"Hocam, kahve makinesi yine bozuk. Bu nöbeti adrenalinle döndüreceğiz.": "ses/ercan/e113.mp3",
"Geçen hafta bir intörn monitör kablosunu şarj aleti sandı. Sen iyisin, merak etme.": "ses/ercan/e114.mp3",
"Nöbet bitince simit benden hocam. Çay da senden.": "ses/ercan/e115.mp3",
"Bu hızla gidersen başhekim seni yanına alır, haberin olsun.": "ses/ercan/e116.mp3",
"Yirmi bir yıldır buradayım, şu sandalye hâlâ gıcırdıyor. Bir o değişmedi.": "ses/ercan/e117.mp3",
"Hocam, kızım da tıp istiyor. Bu gece eve gidince 'iyi düşün' diyeceğim.": "ses/ercan/e118.mp3",
"Daha fazlasını söylersem sen gitmiş olursun hocam.": "ses/ercan/e119.mp3",
"Hocam, EKG'yi çekeyim mi, yoksa önce öykü mü alıyorsun?": "ses/ercan/e120.mp3",
"Çekiyorum hocam, kâğıt birkaç dakikada elinde.": "ses/ercan/e121.mp3",
"Tamam hocam. Ama göğüs ağrısı ilk on dakikayı sever.": "ses/ercan/e122.mp3",
"Gönderiyorum hocam. Bir saat sonra bakarız. Hasta ne yapacak o zamana kadar?": "ses/ercan/e123.mp3",
"Hocam, damar yolunu açıp kan alayım mı?": "ses/ercan/e124.mp3",
"Açıyorum hocam. Kan bekler, damar yolu beklemez.": "ses/ercan/e125.mp3",
"Sonra olmaz hocam, ama sen bilirsin.": "ses/ercan/e126.mp3",
"Hocam, çocuk çok ağrıda. Ağrı kesici yazacak mısın?": "ses/ercan/e127.mp3",
"Veriyorum hocam. Ağrı kesmek bulgunun üstüne örtü çekmez.": "ses/ercan/e128.mp3",
"Tamam hocam. Ama çocuk kıvranıyor.": "ses/ercan/e129.mp3",
"Hocam, bu eski bir yanlış. Ağrı kesmek muayeneyi bozmaz. Not aldım.": "ses/ercan/e130.mp3",
"Hocam, hasta su istiyor. Birkaç yudum versem?": "ses/ercan/e131.mp3",
"Tamam hocam, ağzına bir şey yok.": "ses/ercan/e132.mp3",
"Verdim hocam. Ama ameliyata giderse bu iş sorun çıkarabilir.": "ses/ercan/e133.mp3",
"Hocam, acil çantası elimde. Emir ver, ilacı çekeyim mi, yoksa önce monitör mü?": "ses/ercan/e134.mp3",
"Çekiyorum hocam, hangisi? Emir ver.": "ses/ercan/e135.mp3",
"Bağladım hocam. Ama bu hastada dakika ilaçtan geçer.": "ses/ercan/e136.mp3",
"Hocam, tanı klinik. Tetkik bekleme.": "ses/ercan/e137.mp3",
"Hocam, başı dönüyor, tansiyonu düşük. Nasıl yerleştireyim?": "ses/ercan/e138.mp3",
"Yatırıyorum hocam. Bacaklarını da kaldırdım.": "ses/ercan/e139.mp3",
"Oturtuyorum hocam. Ama tansiyon bu kadar düşükken dik oturtmak iyi olmaz, bir daha düşün.": "ses/ercan/e140.mp3",
"Hocam, saturasyonu doksan sekiz görünüyor ama bu hanımın hâli içime sinmedi. Maske takayım mı?": "ses/ercan/e141.mp3",
"Takıyorum hocam: geri solumasız, on beş litre.": "ses/ercan/e142.mp3",
"Sen bilirsin hocam. Ama saturasyon her zaman doğruyu söylemez.": "ses/ercan/e143.mp3",
"Hocam, kan gazı alayım mı? Makinemiz karbonmonoksiti de ölçüyor.": "ses/ercan/e144.mp3",
"Alıyorum hocam, beş dakikaya sonuç elinde.": "ses/ercan/e145.mp3",
"Peki hocam.": "ses/ercan/e146.mp3",
"Güzel konuştun hocam. Kısa, net, dürüst.": "ses/ercan/e147.mp3",
"Hocam, emin olmadığın şeyi söyleme. Kadın sonra bize hesap sorar.": "ses/ercan/e148.mp3",
"Hocam, bir cümle de olsa bilgi ver. Korkan insan kapıda bekleyemez.": "ses/ercan/e149.mp3",
"Hocam, kadına bir dakika ver, yoksa güvenliği çağırmak zorunda kalacağım.": "ses/ercan/e150.mp3",
"Hocam, ağrı kesici dedin; sözünü tut, unutma.": "ses/ercan/e151.mp3",
"Hocam, muayene bitmeden 'önemli değil' deme.": "ses/ercan/e152.mp3",
"Hocam, sesini yükseltene sesini yükseltme. İki cümle bilgi, sorun biter.": "ses/ercan/e153.mp3",
"Hocam, çocuk sinirlendi. Bir dakikanı ver, yoksa iş büyür.": "ses/ercan/e154.mp3",
"Doğru. Anneyi yanında tut, hasta sakinleşir.": "ses/ercan/e155.mp3",
"Hocam, buna basit denmez. Anneyi de kandırma, kendini de.": "ses/ercan/e156.mp3",
"Hocam, kadını kapıya ben götürürüm, sen hastaya dön. Ama bir cümle bilgi verseydin kendisi çıkardı.": "ses/ercan/e157.mp3",
"Hocam, anneye bir cümle, sonra hastaya dön.": "ses/ercan/e158.mp3",
"İyi yakaladın hocam. Müdahaleden 'evdekileri çağır' emrini de ver, 112 ile ben ilgilenirim.": "ses/ercan/e159.mp3",
"Hocam, aynı gece, aynı ev, herkesin başı ağrıyor... Bunu grip diye geçme.": "ses/ercan/e160.mp3",
"Hocam, adamın da rengi atmış. Bekleme salonunda bayılırsa iki hastamız olur.": "ses/ercan/e161.mp3",
"Hocam, adamın rengi atmış. Ona da bir bakmamız lazım.": "ses/ercan/e162.mp3",
"Kırmızı alan, tamam. Sedyeyi itiyorum hocam.": "ses/ercan/e163.mp3",
"Sarı alan, tamam. Perdeli bölmeye alıyorum.": "ses/ercan/e164.mp3",
"Hocam, bu hastayı kırmızıya aldık ama sarıda da olurdu. Kırmızıdaki yatak başka hastaya lazım olabilir.": "ses/ercan/e165.mp3",
"Hocam, bu senin hastan. Portresine tıklayınca görünüşünü okursun. Üstündeki rozetler hastaya yaptıklarını gösterir.": "ses/ercan/e166.mp3",
"Vitaller kapalı, ölçmeden göremezsin. Monitöre bağla ya da tek tek ölç. Her ölçüm vaka saatinden zaman yer.": "ses/ercan/e167.mp3",
"Kararların burada: bir öykü, iki geçmiş, üç muayene, dört tetkik, beş müdahale, altı tanı. N tuşu e-Nabız'ı açar.": "ses/ercan/e168.mp3",
"Hastaya istediğini yazarak sorabilirsin. Anlamazsa sana en yakın soruları önerir.": "ses/ercan/e169.mp3",
"Üst çubuk dikkat isteyen her şeyi gösterir: kötüleşme, gelen sonuç, bekleyen tetkik. Tıklayınca oraya gidersin. Space ile duraklatırsın.": "ses/ercan/e170.mp3",
"Ben buradayım. Takılırsan bana danış, puanını kırmam ama cevabı da vermem. Arada ben de sana soru sorarım.": "ses/ercan/e171.mp3",
"Tetkik sonuçları arka planda gelir. Sonucu bekle düğmesi saati ileri sarar, alttaki şerit neyin ne zaman geleceğini gösterir.": "ses/ercan/e172.mp3",
"Bulgu topladıkça düşünceler açılır. Tanı sekmesindeki dolaba en fazla üçünü koy, kanıt geldikçe güçlenir ya da zayıflar. Hazırsan saat şimdi başlıyor.": "ses/ercan/e173.mp3"
};
